# Generated by Django 3.1.2 on 2020-10-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='correlative_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courses', verbose_name='Correlativo'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='correlative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lessons', verbose_name='Correlativo'),
        ),
    ]
