# Generated by Django 3.1.2 on 2020-10-29 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201028_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationstudentscourses',
            options={'verbose_name': 'Relación Estudiante-Curso', 'verbose_name_plural': 'Relación Estudiantes-Cursos'},
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.CreateModel(
            name='RelationQuestionsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answers', verbose_name='Respuestas')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questions', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Relación Estudiante-Curso',
                'verbose_name_plural': 'Relación Estudiantes-Cursos',
            },
        ),
    ]
