from django.utils.translation import ugettext as _

TYPE_QUESTIONS_CHOICES = (
    (0, _('BOOLEAN')), 
    (1, _('MULTIPLE CHOICE, ONE ANSWER CORRECT')), 
    (2, _('MULTIPLE CHOICE, MORE THAN ONE ANSWER IS CORRECT')), 
    (3, _('MULTIPLE CHOICE, MORE THAN ONE ANSWER IS CORRECT, ALL MUST BE ANSWERED CORRECTLY'))
)